### ISSUE TITLE
help find your package

### ISSUE THREAD

**Issue by Scrum** [posthtml/posthtml-atomizer#3]
@charlesbjohnson Hi, I am a posthtml package maintainer, I found your package because you have a posthtml package in dependencies. I think it will be easier for people to find your package if you add it to the list of plugins [here](https://github.com/posthtml/posthtml#plugins) and [here](https://github.com/posthtml/posthtml-plugins/), and of course the first thing to do in the posthtml organization itself - I can move your package to the posthtml organization for more popularity, for this it will be necessary to add me to this repository and then I will transfer it. The package itself will remain under your control.

let me know about any decision you make, i will understand if you are not interested

**Comment by charlesbjohnson** [comment]
Hi @Scrum. I think that makes sense and I've added you as a collaborator. How do you think we should proceed with the npm package?

**Comment by Scrum** [comment]
Hi @charlesbjohnson, unfortunately the co-author’s rights are not enough so that I could transfer your package to the posthtml organization. I need to have status !!! to have access to !!! so that I could move.

At the expense of `npm`, I would be happy to be able to publish, thereby to be able to keep your package up to date or to make critical corrections.

**Comment by Scrum** [comment]
@charlesbjohnson ping

**Comment by Scrum** [comment]
@charlesbjohnson Hi, check access and welcome aboard.
